name: Release

on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: dist-merged  
    - name: Display structure of downloaded files
      run: ls -R
